spring:
  application:
    name: scientist-hunt
  data:
    mongodb:
      uri: mongodb+srv://arjunmudaliyar99_db_user:Arjun123@cluster1.fhzqxt1.mongodb.net/scientisthunt?retryWrites=true&w=majority&appName=Cluster1
      database: scientisthunt
  jackson:
    default-property-inclusion: non_null

server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-stacktrace: never
    include-message: never

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    access-expiry-ms: 900000
    refresh-expiry-ms: 604800000
  security:
    jwt-secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    issuer: scientis-hunt
    access-token-minutes: 15

logging:
  level:
    com.scientishunt: DEBUG
    org.springframework.data.mongodb: DEBUG
